name = "chatgpt-api"
main = "src/index.js"
compatibility_date = "2023-03-03"
usage_model = "bundled"
env = { }
kv_namespaces = [
  { binding = "kv", id = "45fe96cc90c74956ac5815e0e9465204" }
]

[triggers]
crons = [ ]
